# SPDX-FileCopyrightText: 2022 Paul Colby <git@colby.id.au>
# SPDX-License-Identifier: MIT

on: push

jobs:
  minimal:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run post-to-slack action
        uses: ./
        with:
          url: https://example.com/
          text: Test message
          dryRun: true
        id: post
      - name: Validate outputs
        run: |
          [[ "$REQUEST" == '{"text":"Test message"}' ]]
          [[ -z "$RESPONSE" ]] # Dry-run.
        shell: bash
        env:
          REQUEST: ${{  steps.post.outputs.request  }}
          RESPONSE: ${{ steps.post.outputs.response }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - macos-11     # aka macos-latest
          - macos-12
          - ubuntu-18.04
          - ubuntu-20.04 # aka ubuntu-latest
          - ubuntu-22.04
          - windows-2019
          - windows-2022 # aka windows-latest
      fail-fast: false

  exhaustive:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run post-to-slack action
        uses: ./
        with:
          url: ${{ secrets.TEST_EXAMPLE_URL }}
          text: >-
            Complex message with "quotes", 'quotes',
            and {fancy} [symbols] ;)
          channel: '#general'
          username: "Testy \"Tester\" Mc'Testface"
          iconEmoji: ':gh"ost:'
          iconUrl: 'https://example.com/example.png'
          attachments: |
            [
              { "test": 1 },
              { "test": 2 }
            ]
          dryRun: true
        id: post
      - name: Validate outputs
        run: |
          [[ "$REQUEST" == "$expectedRequest" ]]
          [[ -z "$RESPONSE" ]] # Dry-run.
        shell: bash
        env:
          REQUEST: ${{  steps.post.outputs.request  }}
          RESPONSE: ${{ steps.post.outputs.response }}
          expectedRequest: >-
            {"attachments":[{"test":1},{"test":2}],"channel":"#general","text":"Complex
            message with \"quotes\", 'quotes', and {fancy} [symbols] ;)","username":"Testy
            \"Tester\" Mc'Testface"}
    strategy:
      matrix:
        os:
          - macos-10.15
          - macos-11     # aka macos-latest
          - macos-12
          - ubuntu-18.04
          - ubuntu-20.04 # aka ubuntu-latest
          - ubuntu-22.04
          - windows-2019
          - windows-2022 # aka windows-latest
      fail-fast: false
